server:
  port: 9000

#spring:
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          basic-client:
#            registration:
#              client-id: football
#              client-secret: "{noop}SuperSecret"
#              client-authentication-methods: "client_secret_post"
#              authorization-grant-types: "client_credentials"
#              scopes: "football:read"

#spring:
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          football:
#            registration:
#              client-id: "football"
#              client-secret: "{noop}SuperSecret"
#              client-authentication-methods:
#              - "client_secret_post"
#              authorization-grant-types:
#              - "client_credentials"
#              scopes:
#                - "football:read"
#                - "football:admin"

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          football-ui:
            registration:
              client-id: "football-ui"
              client-secret: "{noop}TheSecretSauce"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:9080/login/oauth2/code/football-ui"
              scopes:
                - "openid"
                - "profile"
                - "football:read"
                - "football:admin"
            require-authorization-consent: true
    User:
      name: "user"
      password: "password"
